apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    name: prometheus-configmap
data:
  prometheus.yml: |-
    global:
      scrape_interval:     30s
      evaluation_interval: 30s

    scrape_configs:
      - job_name: 'local-prometheus'
        static_configs:
        - targets: ['10.135.93.16:9091']

      - job_name: 'prodserver'
        static_configs:
        - targets: ['194.135.93.16:9091']
