
def git_url = 'https://github.com/rjmsas/k8-deployment.git'
def git_branch = 'main'

pipeline
{
    agent
    {
        label 'k8'
    }

    stages
    {
        stage('deploy')
        {
            
            steps{
                   sh '''
                   pwd
                   ls -ltr                   
                   cd grafana
                   kubectl delete -f grafana-deploy.yml | exit 0
                   kubectl apply -f grafana-deploy.yml
                   '''
               }
        
        }
    }
}
